version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React Vite app..."
      - npm run build
  post_build:
    commands:
      - echo "Syncing build files to S3..."
      - aws s3 sync dist/ s3://chatpulse-frontend-bucket --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E3I0Y9RP3FPSV9 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
